on:
  pull_request:
    paths:
      - '**.php'
      - '**.yaml'
      - 'composer.json'
      - 'composer.lock'
name: PHP - Check coverage
jobs:
  coverage:
    name: Test & Check coverage
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        options: --name=mysql
        ports:
          - 3309:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_todolist_test_test
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, mysql, apcu, intl, gd, soap
          ini-values: memory_limit=8G, date.timezone=Europe/Paris
          coverage: pcov
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer install --no-scripts --no-interaction --prefer-dist --optimize-autoloader --no-suggest --ansi
      - name: Run migrations
        run: |
          mysql -h 127.0.0.1 --port 3309 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS test_todolist_test_test;'
          bin/console doctrine:schema:create --env=github
      - name: Run Unit Tests
        run: |
          bin/console cache:warmup --env=test --ansi
          bin/console doctrine:fixtures:load --no-interaction
          mkdir -p build/cov_partials
          bin/phpunit -d memory_limit=4G -c phpunit.xml.dist --coverage-text=tests/coverage.txt --colors=always
      - name: Send coverage email
        if: always()
        run: |
          bin/console coverage:send-email